// <auto-generated />
using System;
using Cuba_Staterkit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuba_Staterkit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203090153_addtable")]
    partial class addtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cuba_Staterkit.Models.t_account", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("inactive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("user_id");

                    b.ToTable("t_account");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_attendance", b =>
                {
                    b.Property<int>("attendance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("clock_in")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("clock_out")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("attendance_id");

                    b.HasIndex("employee_id");

                    b.ToTable("t_attendance");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("base_salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("employee_id");

                    b.HasAlternateKey("username");

                    b.HasIndex("position_id");

                    b.ToTable("t_employee");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_position", b =>
                {
                    b.Property<int>("position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("position_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("salary_max")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("salary_min")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("position_id");

                    b.ToTable("t_position");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_attendance", b =>
                {
                    b.HasOne("Cuba_Staterkit.Models.t_employee", "Employee")
                        .WithMany("Attendance")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_employee", b =>
                {
                    b.HasOne("Cuba_Staterkit.Models.t_position", "Position")
                        .WithMany("Employee")
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuba_Staterkit.Models.t_account", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("Cuba_Staterkit.Models.t_employee", "username")
                        .HasPrincipalKey("Cuba_Staterkit.Models.t_account", "username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_account", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_employee", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Cuba_Staterkit.Models.t_position", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
